import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//test
import { Client } from "@notionhq/client"




const Home: NextPage = () => {


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Hello</h1>
      </main>
    </div>
  )
}


export default Home;

// export async function getStaticProps() {

//   const test = process.env.NOTION_API_KEY as string;
//   console.log(test)  
//   return {
//     props: {},
//   }
// }